const lookupMed = [
    {
	    "name": "ACETAMINOPHEN",
        "class_code": "",
        "class_label": "TEST",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ACETAMINOPHEN/CODEINE",
        "class_code": "OPIOID",
        "class_label": "Opioid",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk":false
    },
    {
	    "name": "ACETAZOLAMIDE",
        "class_code": "DIURETIC",
        "class_label": "Diuretic",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ALBUTEROL",
        "class_code": "ALBUTEROL",
        "class_label": "Albuterol (Rescue)",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ALPRAZOLAM",
        "class_code": "BENZO",
        "class_label": "Benzodiazepine",
        "beers_know": "ALPRAZOLAM should be avoided.\nIn older adults,ALPRAZOLAM use increases risks of abuse, misuse, and addiction. ALPRAZOLAM also increases the risk of cognitive impairment, delirium, falls, fractures, and motor vehicle crashes in older adults.",        "beers_do": "Speak with your doctor about tapering you off ALPRAZOLAM and choosing another medication to treat your condition(s).",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "AMIODARONE HCL",
        "class_code": "ANTIARRHYTMIC",
        "class_label": "Antiarrhytmic",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "AMITRIPTYLINE HCL",
        "class_code":         "beers_TCA",
        "class_label": "⚠️ Beers: TCA",
        "beers_know": "AMITRIPTYLINE should be avoided. \nIn older adults, AMITRIPTYLINE use has been reported with increasing risks of dementia, delirium, falls, and urinary or GI complications.",
        "beers_do": "Speak with your doctor about stopping AMITRIPTYLINE and choosing another medication to treat your condition(s).",
        "serotonin_risk": true,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "AMLODIPINE",
        "class_code": "CCB",
        "class_label": "CCB",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "AMLODIPINE BESYLATE-BENAZEPRIL",
        "class_code": "CCB-ACEI",
        "class_label": "CCB/ACE Inhibitor",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "AMOXICILLIN",
        "class_code": "PCN",
        "class_label": "Penicillin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "AMOXICILLIN & POTASSIUM CLAVULANATE",
        "class_code": "PCN",
        "class_label": "Penicillin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "AMPHETAMINE‑DEXTROAMPHETAMINE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ARIPIPRAZOLE LAUROXIL (ARISTADA)",
        "class_code": "ANTIPSYCHOTIC",
        "class_label": "Antipsychotic — QT Risk",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ASPIRIN",
        "class_code": "ANTIPLATELET",
        "class_label": "Antiplatelet",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ATORVASTATIN CALCIUM",
        "class_code": "STATIN",
        "class_label": "Statin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "AZITHROMYCIN",
        "class_code": "AZITHROMYCIN",
        "class_label": "Azithromycin — QT Risk",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "BENZTROPINE MESYLATE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "BIMATOPROST",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "BREXPIPRAZOLE",
        "class_code": "ANTIPSYCHOTIC",
        "class_label": "Antipsychotic — QT Risk",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "BUDESONIDE‑GLYCOPYRROLATE‑FORMOTEROL FUMARATE (BREZTRI AEROSPHERE)",
        "class_code": "LABA",
        "class_label": "LABA-Containing Inhaler",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "BUMETANIDE",
        "class_code": "DIURETIC",
        "class_label": "Diuretic",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "BUPRENORPHINE HCL‑NALOXONE HCL DIHYDRATE",
        "class_code": "OPIOID",
        "class_label": "Opioid",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "BUPROPION HCL",
        "class_code": "BUPROPION",
        "class_label": "Bupropion (Serotonin Risk)",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": true,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "BUSPIRONE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": true,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CALCITRIOL",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CANDESARTAN",
        "class_code": "ARB",
        "class_label": "ARB",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CARVEDILOL",
        "class_code": "BB_NONSEL",
        "class_label": "Beta-Blocker (Non-Selective) ⚠️",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CELECOXIB",
        "class_code": "NSAID",
        "class_label": "NSAID",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CETIRIZINE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CHLORHEXIDINE GLUCONATE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CHLORTHALIDONE",
        "class_code": "DIURETIC",
        "class_label": "Diuretic",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CITALOPRAM",
        "class_code": "SSRI",
        "class_label": "SSRI",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": true,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CLINDAMYCIN HCL",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CLONAZEPAM",
        "class_code": "BENZO",
        "class_label": "Benzodiazepine",
        "beers_know": "CLONAZEPAM should be avoided.\nIn older adults, CLONAZEPAM use increases risks of abuse, misuse, and addiction. CLONAZEPAM also increases the risk of cognitive impairment, delirium, falls, fractures, and motor vehicle crashes in older adults.",
        "beers_do": "Speak with your doctor about tapering you off CLONAZEPAM and choosing another medication to treat your condition(s).",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "CLONIDINE HCL",
        "class_code":         "beers_cALPHA",
        "class_label": "⚠️ Beers: Central Alpha Agonist",
        "beers_know": "CLONIDINE is not recommended in older adults because the medication puts patients at a higher risk CNS adverse events and orthostatic hypotension.",
        "beers_do": "Speak with your doctor about stopping CLONIDINE and adjusting your blood pressure medications.",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CLOPIDOGREL",
        "class_code": "CLOPIDOGREL",
        "class_label": "Clopidogrel ⚠️",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "CYCLOBENZAPRINE",
        "class_code": "MUSCLE_RELAXANT",
        "class_label": "Muscle Relaxant",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "DABIGATRAN",
        "class_code": "ANTICOAGULANT",
        "class_label": "Anticoagulant (Warfarin/DOAC)",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "DAPAGLIFLOZIN",
        "class_code": "SGLT2",
        "class_label": "SGLT-2 Inhibitor",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "DIAZEPAM",
        "class_code": "BENZO",
        "class_label": "Benzodiazepine",
        "beers_know": "DIAZEPAM should be avoided.\nIn older adults, DIAZEPAM use increases risks of abuse, misuse, and addiction. DIAZEPAM also increases the risk of cognitive impairment, delirium, falls, fractures, and motor vehicle crashes in older adults.",
        "beers_do": "Speak with your doctor about tapering you off DIAZEPAM and choosing another medication to treat your condition(s).",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "DICLOFENAC",
        "class_code": "NSAID",
        "class_label": "NSAID",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "DICYCLOMINE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "DILTIAZEM HCL",
        "class_code": "CCB",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "DOXEPIN",
        "class_code":         "beers_TCA",
        "class_label": "⚠️ Beers: TCA",
        "beers_know": "DOXEPIN should be avoided. \nIn older adults, DOXEPIN use has been reported with increasing risks of dementia, delirium, falls, and urinary or GI complications.",
        "beers_do": "Speak with your doctor about stopping DOXEPIN and choosing another medication to treat your condition(s).",
        "serotonin_risk": true,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "DULOXETINE",
        "class_code": "SNRI",
        "class_label": "SNRI",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": true,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ELIQUIS",
        "class_code": "ANTICOAGULANT",
        "class_label": "Anticoagulant (Warfarin/DOAC)",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "EMPAGLIFLOZIN",
        "class_code": "SGLT2",
        "class_label": "SGLT-2 Inhibitor",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ESCITALOPRAM",
        "class_code": "SSRI",
        "class_label": "SSRI",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ESOMEPRAZOLE",
        "class_code": "PPI_OTHER",
        "class_label": "PPI — Other ⚠️",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ESTRADIOL",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ESZOPICLONE",
        "class_code": "Z-HYPNO",
        "class_label": "⚠️ Beers: Z-Hypnotic",
        "beers_know": "ESZOPICLONE should be avoided in older adults.\nESZOPICLONE exerts little improvement in sleep quality and duration, while increasing the risk for delirium, falls, fractures, increased emergency room visits/hospitalizations, and/or motor vehicle crashes.",
        "beers_do": "Speak with your doctor about tapering you off ESZOPICLONE and choosing another medication to treat your condition(s).",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "EZETIMIBE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "FAMOTIDINE",
        "class_code": "H2RA",
        "class_label": "H2 Receptor Antagonist",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "FLUOXETINE",
        "class_code": "SSRI",
        "class_label": "SSRI",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": true,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "FLUTICASONE PROPIONATE",
        "class_code": "ICS",
        "class_label": "Inhaled Corticosteroid",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "FLUTICASONE‑UMECLIDINIUM‑VILANTEROL (TRELEGY ELLIPTA)",
        "class_code": "LABA",
        "class_label": "LABA-Containing Inhaler",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "Fluticasone–Salmeterol",
        "class_code": "LABA",
        "class_label": "LABA-Containing Inhaler",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "FUROSEMIDE",
        "class_code": "DIURETIC",
        "class_label": "Diuretic",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "GABAPENTIN",
        "class_code": "GABAPENTINOID",
        "class_label": "Gabapentin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "GLIMEPIRIDE",
        "class_code":         "beers_SULFONYLUREA",
        "class_label": "⚠️ Beers: Sulfonylurea",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "GLIPIZIDE",
        "class_code":         "beers_SULFONYLUREA",
        "class_label": "⚠️ Beers: Sulfonylurea",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "HYDROCHLOROTHIAZIDE",
        "class_code": "DIURETIC",
        "class_label": "Diuretic",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "HYDROCODONE/ACETAMINOPHEN",
        "class_code": "",
        "class_label": "OPIOID",
        "beers_know": "Opioid",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "IBUPROFEN",
        "class_code": "NSAID",
        "class_label": "NSAID",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "INSULIN ASPART (NOVOLOG FLEXPEN)",
        "class_code": "Insulin",
        "class_label": "Insulin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "INSULIN GLARGINE",
        "class_code": "Insulin",
        "class_label": "Insulin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "INSULIN LISPRO (ADMELOG SOLOSTAR)",
        "class_code": "Insulin",
        "class_label": "Insulin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "INSULIN REGULAR (HUMULIN R)",
        "class_code": "Insulin",
        "class_label": "Insulin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "IPRATROPIUM BROMIDE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "IRBESARTAN",
        "class_code": "ARB",
        "class_label": "ARB",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ISOSORBIDE MONONITRATE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LAMOTRIGINE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LATANOPROST",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LETROZOLE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LEVOFLOXACIN",
        "class_code": "FLUOROQUINOLONE",
        "class_label": "Fluoroquinolone — QT Risk",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LEVOTHYROXINE SODIUM",
        "class_code": "LEVOTHYROXINE",
        "class_label": "Levothyroxine",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LINAGLIPTIN‑METFORMIN",
        "class_code": "DPP4",
        "class_label": "DPP-4 Inhibitor",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LISDEXAMFETAMINE DIMESYLATE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LISINOPRIL",
        "class_code": "ACEI",
        "class_label": "ACE Inhibitor",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LISINOPRIL & HYDROCHLOROTHIAZIDE",
        "class_code": "ACEI",
        "class_label": "ACE Inhibitor",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LORATADINE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LORAZEPAM",
        "class_code": "BENZO",
        "class_label": "Benzodiazepine",
        "beers_know": "LORAZEPAM should be avoided.\nIn older adults, LORAZEPAM use increases risks of abuse, misuse, and addiction. LORAZEPAM also increases the risk of cognitive impairment, delirium, falls, fractures, and motor vehicle crashes in older adults.",
        "beers_do": "Speak with your doctor about tapering you off LORAZEPAM and choosing another medication to treat your condition(s).",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "LOSARTAN",
        "class_code": "ARB",
        "class_label": "ARB",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "LOSARTAN POTASSIUM & HYDROCHLOROTHIAZIDE",
        "class_code": "ARB",
        "class_label": "ARB",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "MELATONIN",
        "class_code": "SUPPLEMENT",
        "class_label": "Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "MELOXICAM",
        "class_code": "NSAID",
        "class_label": "NSAID",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "MELOXICAM",
        "class_code": "NSAID",
        "class_label": "NSAID",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "METAXALONE",
        "class_code": "MUSCLE_RELAXANT",
        "class_label": "Muscle Relaxant",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "METFORMIN",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "METHOCARBAMOL",
        "class_code": "MUSCLE_RELAXANT",
        "class_label": "Muscle Relaxant",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "METHYLPREDNISOLONE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "METOPROLOL",
        "class_code": "BB_SEL",
        "class_label": "Beta-Blocker (Selective) ⚠️",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "MONTELUKAST SODIUM",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "MORPHINE",
        "class_code": "OPIOID",
        "class_label": "Opioid",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "MOUNJARO",
        "class_code": "GLP-1",
        "class_label": "GLP-1",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "MULTIPLE VITAMINS W/ MINERALS (CENTRUM SILVER) ",
        "class_code": "SUPPLEMENT",
        "class_label": "Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "MULTIPLE VITAMINS WITH MINERALS",
        "class_code": "SUPPLEMENT",
        "class_label": "Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "MULTIVITAMINS",
        "class_code": "SUPPLEMENT",
        "class_label": "Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "NIFEDIPINE",
        "class_code": "CCB",
        "class_label": "Calcium channel blocker",
        "beers_know": "NIFEDIPINE is not recommended in older adults because NIFEDIPINE may drop your blood pressure (BP) too quick. This rapid BP drop may result in reflex tachycardia, which causes an increased heart rate and may pump blood away from your heart. This may put you at an increased risk for chest pain and a heart attack.", 
        "beers_do": "-Speak with your doctor about stopping NIFEDIPINE and adjusting your blood pressure medications to ensure reaching goal blood pressure",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "NITROGLYCERIN",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "NORTRIPTYLINE",
        "class_code":         "beers_TCA",
        "class_label": "⚠️ Beers: TCA",
        "beers_know": "NORTRIPTYLINE should be avoided. \nIn older adults, NORTRIPTYLINE use has been reported with increasing risks of dementia, delirium, falls, and urinary or GI complications.",
        "beers_do": "Speak with your doctor about stopping NORTRIPTYLINE and choosing another medication to treat your condition(s).",
        "serotonin_risk": true,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "OLMESARTAN MEDOXOMIL",
        "class_code": "ARB",
        "class_label": "ARB",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "OMEPRAZOLE",
        "class_code": "PPI_OTHER",
        "class_label": "PPI — Other ⚠️",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ONDANSETRON",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "OXYCODONE",
        "class_code": "OPIOID",
        "class_label": "Opioid",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "OXYCODONE/ACETAMINOPHEN",
        "class_code": "OPIOID",
        "class_label": "Opioid",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "OZEMPIC",
        "class_code": "GLP-1",
        "class_label": "GLP-1",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PANTOPRAZOLE SODIUM",
        "class_code": "PPI_PANTO",
        "class_label": "PPI — Pantoprazole ✓",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PAROXETINE",
        "class_code": "SSRI",
        "class_label": "SSRI",
        "beers_know": "PAROXETINE should be avoided. \nIn older adults, PAROXETINE use has been reported with increasing risks of dementia, delirium, falls, and urinary or GI complications.",         
        "beers_do": "Speak with your doctor about stopping PAROXETINE and choosing another medication to treat your condition(s).",
        "serotonin_risk": true,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PIOGLITAZONE HCL",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "POTASSIUM CHLORIDE",
        "class_code": "ELECTROLYTE",
        "class_label": "Electrolyte Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PRAMIPEXOLE DIHYDROCHLORIDE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PRAVASTATIN SODIUM",
        "class_code": "STATIN",
        "class_label": "Statin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PREDNISONE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PREGABALIN",
        "class_code": "GABAPENTINOID",
        "class_label": "Gabapentinoid",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "PRIMIDONE",
        "class_code": "BARBITURATE",
        "class_label": "Barbiturate",
        "beers_know": "PRIMIDONE should be avoided. \nIn older adults, PRIMIDONE has a high rate of physical dependence, tolerance to sleep benefits, and greater risk of overdose at low dosages.",
        "beers_do": "Speak with your doctor about stopping PRIMIDONE and choosing another medication to treat your condition(s).",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PROGESTERONE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PROMETHAZINE HCL",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "PROPRANOLOL",
        "class_code": "BB_NONSEL",
        "class_label": "Beta-Blocker (Non-Selective) ⚠️",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "QUETIAPINE FUMARATE",
        "class_code":         "beers_AAP",
        "class_label": "⚠️ Beers: Antipsychotic",
        "beers_know": "QUETIAPINE should be avoided. \nIn older adults, QUETIAPINE use has been reported with an increased risk of stroke and greater rate of cognitive decline and mortality in persons with dementia. Additional evidence suggests association of increased risk between antipsychotic medication and mortality independent of dementia.",         "beers_do": "Avoid QUETIAPINE for behavioral problems of dementia or delirium unless documented nonpharmacologic options (e.g., behavioral interventions) have failed and/or the patient is threatening substantial harm to self or others. \n[If used] Speak with your doctor about taking you off QUETIAPINE and assess ongoing need and/or lowest effective dose.",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "RANOLAZINE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ORGOVYX",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "KISQALI",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "RISEDRONATE SODIUM",
        "class_code": "BISPHOSPHONATE",
        "class_label": "Bisphosphonate",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "RIVAROXABAN (XARELTO)",
        "class_code": "ANTICOAGULANT",
        "class_label": "Anticoagulant (Warfarin/DOAC)",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "ROSUVASTATIN",
        "class_code": "STATIN",
        "class_label": "Statin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "SERTRALINE",
        "class_code": "SSRI",
        "class_label": "SSRI",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": true,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "SIMVASTATIN",
        "class_code": "STATIN",
        "class_label": "Statin",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "SITAGLIPTIN",
        "class_code": "DPP4",
        "class_label": "DPP-4 Inhibitor",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "SITAGLIPTIN PHOSPHATE‑METFORMIN HCL (JANUMET)",
        "class_code": "DPP4",
        "class_label": "DPP-4 Inhibitor",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "STIOLTO RESPIMAT",
        "class_code": "LABA",
        "class_label": "LABA-Containing Inhaler",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "SUCRALFATE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "SULFAMETHOXAZOLE/TRIMETHOPRIM",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "TACROLIMUS",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "TAMSULOSIN HCL",
        "class_code": "TAMSULOSIN",
        "class_label": "Tamsulosin/Alpha-Blocker",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "TIMOLOL MALEATE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "TIZANIDINE",
        "class_code": "MUSCLE_RELAXANT",
        "class_label": "Muscle Relaxant",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "TOPIRAMATE",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "TRAMADOL",
        "class_code": "OPIOID",
        "class_label": "Opioid",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": true,
        "bleeding_risk": false,
        "resp_risk": true,
        "cns_risk": true
    },
    {
	    "name": "TRAZODONE",
        "class_code": "TRAZODONE",
        "class_label": "Trazodone (Serotonin Risk)",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": true,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "UMECLIDINIUM-VILANTEROL",
        "class_code": "LABA",
        "class_label": "LABA-Containing Inhaler",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VALACYCLOVIR HCL",
        "class_code": "",
        "class_label": "",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VALSARTAN",
        "class_code": "ARB",
        "class_label": "ARB",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VALSARTAN‑HYDROCHLOROTHIAZIDE",
        "class_code": "ARB",
        "class_label": "ARB",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VENLAFAXINE",
        "class_code": "SNRI",
        "class_label": "SNRI",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": true,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VITAMIN B COMPLEX",
        "class_code": "SUPPLEMENT",
        "class_label": "Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VITAMIN B COMPLEX‑C",
        "class_code": "SUPPLEMENT",
        "class_label": "Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VITAMIN B‑12",
        "class_code": "SUPPLEMENT",
        "class_label": "Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VITAMIN C",
        "class_code": "SUPPLEMENT",
        "class_label": "Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VITAMIN D3",
        "class_code": "SUPPLEMENT",
        "class_label": "Supplement",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "VITAMIN E",
        "class_code": "SUPPLEMENT_BLEEDING",
        "class_label": "Supplement (Bleeding Risk) ⚠️",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": false,
        "resp_risk": false,
        "cns_risk": false
    },
    {
	    "name": "WARFARIN",
        "class_code": "ANTICOAGULANT",
        "class_label": "Anticoagulant (Warfarin/DOAC)",
        "beers_know": "",
        "beers_do": "",
        "serotonin_risk": false,
        "bleeding_risk": true,
        "resp_risk": false,
        "cns_risk": false
    }
];
const lookupCon = [
    {
        "name": "High Blood Pressure"
    },
    {
        "name": "Diabetes"
    }
];